### PR TITLE
fix(PeriphDrivers): Flip strong vs weak pull-up bit values

### PR DESCRIPTION
**Pull request by Jake-Carter**
### Description

Apparently most UGs have this flipped.  _Strong_ should set the `ps` field to 0, while _weak_ should set it to `1`.

### Checklist Before Requesting Review

- [ ] PR Title follows correct guidelines.
- [ ] Description of changes and all other relevant information.
- [ ] (Optional) Link any related GitHub issues [using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
- [ ] (Optional) Provide info on any relevant functional testing/validation.  For API changes or significant features, this is not optional.

### CODE REVIEW

**Comment by Jake-Carter** [comment]
Pending final confirmation...  don't merge yet

**Review by sihyung-maxim — APPROVED** [review]
How was this unnoticed for so long lol

**Comment by perkinsmg** [comment]
There are lots of instances where we use the enums which will now have the opposite effect to what they did before.
Mostly that's probably good, because they were probably not working correctly before.
But in at least the case of the MXC_GPIO_PAD_PULL_UP used in pins_me18.c for the UART signals, Kevin's check-in message said he was adding a weak pull-up, and Lorne recommends a weak pull-up, so I think we should change these to weak to preserve the old behaviour.

**Comment by Jake-Carter** [comment]
> There are lots of instances where we use the enums which will now have the opposite effect to what they did before. Mostly that's probably good, because they were probably not working correctly before. But in at least the case of the MXC_GPIO_PAD_PULL_UP used in pins_me18.c for the UART signals, Kevin's check-in message said he was adding a weak pull-up, and Lorne recommends a weak pull-up, so I think we should change these to weak to preserve the old behaviour.

@perkinsmg updated in https://github.com/analogdevicesinc/msdk/pull/1145/commits/1717e1a721927ac4efddb5189e64570bfbc2b9da

**Pull request merged**
