### PR TITLE
feat(Examples): Add dedicated UART_DMA example to MAX32650, MAX32655, MAX32665, MAX32670, MAX32672, MAX32690, and MAX78000

### PR DESCRIPTION
**Pull request by ozan956**
# UART_DMA Example

## Description

Due to the changes in DMA, UART examples are not working with DMA. This was stated both in the issues raised in the MSDK repository and in the tickets sent to us (Customer Support Team). So, @Jake-Carter and I developed a new example called UART_DMA.

The example has been added and tested for the following boards:

- **MAX32650**
- **MAX32655**
- **MAX32665**
- **MAX32670**
- **MAX32672**
- **MAX32690**
- **MAX78000**

### CODE REVIEW

**Comment by sihyung-maxim** [comment]
Could you merge the latest UART changes from main into your fork? Some UART clock source fixes were recently made. Once you do, I can help verify the examples again.

**Comment by ozan956** [comment]
I have merged the latest changes.

**Comment by ozan956** [comment]
> Could you merge the latest UART changes from main into your fork? Some UART clock source fixes were recently made. Once you do, I can help verify the examples again.

I have merged latest changes. @sihyung-maxim

**Review by Jake-Carter — APPROVED** [review]
Thanks @ozan956 

FYI updated project files using latest [MSDKGen](https://github.com/Analog-Devices-MSDK/MSDKGen) (https://github.com/analogdevicesinc/msdk/pull/1115/commits/dbcc06713fc766111b121aab6e7d986e9281cc26) and updated copyrights (https://github.com/analogdevicesinc/msdk/pull/1115/commits/2adea94ebb3b5a2fd24337a2b3b0c5617861dc4a).

**Review by Jake-Carter — COMMENTED** [review]
We should probably clean up the `UART` example as well to remove the DMA code and point customers to this instead

**Review by sihyung-maxim — APPROVED** [review]

**Comment by sihyung-maxim** [comment]
Mouthful of a PR name

**Pull request merged**
