### PR TITLE
fix(Other): Misc Fixes from Feb 2024 Release Testing

### PR DESCRIPTION
**Pull request by Jake-Carter**
### Checklist Before Requesting Review

- [ ] PR Title follows correct guidelines.
- [ ] Description of changes and all other relevant information.
- [ ] (Optional) Link any related GitHub issues [using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
- [ ] (Optional) Provide info on any relevant functional testing/validation.  For API changes or significant features, this is not optional.

### CODE REVIEW

**Comment by sihyung-maxim** [comment]
Some of these workflows are going to fail due to the GitHub org move and different token accesses.

**Comment by Jake-Carter** [comment]
I don't think we should blacklist everything (https://github.com/analogdevicesinc/msdk/pull/925/commits/9c41009105b798fa09284a244c13f51bb648edd4).  

Just `ffconf.h`

**Review by sihyung-maxim — APPROVED** [review]

**Comment by sihyung-maxim** [comment]
> I don't think we should blacklist everything ([9c41009](https://github.com/analogdevicesinc/msdk/commit/9c41009105b798fa09284a244c13f51bb648edd4)).
> 
> Just `ffconf.h`

Ope, okay. Just saw this message, disregard my approval.

**Pull request merged**
