### PR TITLE
Workflows: clang-format-run: Fixed directory exclusions in find command.

### PR DESCRIPTION
**Pull request by sihyung-maxim**
Fixed regex pattern in find command for clang-format-run.sh.

### CODE REVIEW

**Review by Jacob-Scheiffler — APPROVED** [review]

**Review by kevin-gillespie — APPROVED** [review]

**Review by Jake-Carter — CHANGES_REQUESTED** [review]
We should make the runner match the checker exactly:

https://github.com/Analog-Devices-MSDK/msdk/blob/f1942550e0d9ce5cc0cb3727cdfe15879d3bef40/.github/workflows/clang-format-check.yml#L56

CNN generated files should be skipped

**Review by Jake-Carter — APPROVED** [review]
Looks good!  Thanks @sihyung-maxim

**Pull request merged**
